//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBook {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorsMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneBook.ErrorsMessages", typeof(ErrorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;obj&apos; isn&apos;t Person..
        /// </summary>
        internal static string Person_equals_not_person_argument {
            get {
                return ResourceManager.GetString("Person_equals_not_person_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Length of string of parameter &apos;comment&apos; should be less then {0}.
        /// </summary>
        internal static string Person_new_comment_too_large_formating {
            get {
                return ResourceManager.GetString("Person_new_comment_too_large_formating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;name&apos; shouldn&apos;t be the empty string..
        /// </summary>
        internal static string Person_new_empty_name {
            get {
                return ResourceManager.GetString("Person_new_empty_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection of parameter &apos;records&apos; constist one or more not correct record. Possible it is a few records having equal captions. .
        /// </summary>
        internal static string Person_new_records_not_correct {
            get {
                return ResourceManager.GetString("Person_new_records_not_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Record types in parameter &apos;recordTypes&apos; shouldn&apos;t repeated..
        /// </summary>
        internal static string PhoneBook_new_repeated_record_types {
            get {
                return ResourceManager.GetString("PhoneBook_new_repeated_record_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;caption&apos; shouldn&apos;t be the empty string.
        /// </summary>
        internal static string Record_new_empty_caption {
            get {
                return ResourceManager.GetString("Record_new_empty_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;regexFilter&apos; shouldn&apos;t be the empty string.
        /// </summary>
        internal static string RecordType_new_empty_regex_filter {
            get {
                return ResourceManager.GetString("RecordType_new_empty_regex_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;typeName&apos; shouldn&apos;t be the empty string..
        /// </summary>
        internal static string RecordType_new_empty_type_name {
            get {
                return ResourceManager.GetString("RecordType_new_empty_type_name", resourceCulture);
            }
        }
    }
}
