//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberLife {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberLife.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экземпляр метадаты содержит недопустимый ключ {0}.
        /// </summary>
        internal static string BadInputMetadata {
            get {
                return ResourceManager.GetString("BadInputMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий сезон изменён на .
        /// </summary>
        internal static string ChangeSeason {
            get {
                return ResourceManager.GetString("ChangeSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создаётся экзмепляр {0}.
        /// </summary>
        internal static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий сезон: {0}.
        /// </summary>
        internal static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактор глубины равен {0}.
        /// </summary>
        internal static string DepthFactorCalc {
            get {
                return ResourceManager.GetString("DepthFactorCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод {0} успешно завершён.
        /// </summary>
        internal static string EndMethod {
            get {
                return ResourceManager.GetString("EndMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GenotypeState не содержит ключа Action,либо ключ предназначался для иного класса .
        /// </summary>
        internal static string GenotypeStateAction {
            get {
                return ResourceManager.GetString("GenotypeStateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ GenotypeState не был найден в метадате LifeFormMetadata  .
        /// </summary>
        internal static string GenotypeStateNotFound {
            get {
                return ResourceManager.GetString("GenotypeStateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрошена метадата класса {0}.
        /// </summary>
        internal static string GetMetadata {
            get {
                return ResourceManager.GetString("GetMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрошен экземпляр Place класса {0}.
        /// </summary>
        internal static string GetPlace {
            get {
                return ResourceManager.GetString("GetPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экзмепляр {0} был равен null {1}.
        /// </summary>
        internal static string NullArgument {
            get {
                return ResourceManager.GetString("NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экземпляр {0} был успешно создан.
        /// </summary>
        internal static string OkConstructor {
            get {
                return ResourceManager.GetString("OkConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняем {0}.GetEffects | Point X = {1},Y = {2} .
        /// </summary>
        internal static string PhenomenGetEffects {
            get {
                return ResourceManager.GetString("PhenomenGetEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняем {0}.IsIn.
        /// </summary>
        internal static string PhenomenIsIn {
            get {
                return ResourceManager.GetString("PhenomenIsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполняем {0}.Update .
        /// </summary>
        internal static string PhenomenUpdate {
            get {
                return ResourceManager.GetString("PhenomenUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экземпляр Point не найден в текущем Place  .
        /// </summary>
        internal static string PointNotFound {
            get {
                return ResourceManager.GetString("PointNotFound", resourceCulture);
            }
        }
    }
}
