// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Simple2DWorld.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CyberLife.Protobuff.Simple2DWorld {

  /// <summary>Holder for reflection information generated from Simple2DWorld.proto</summary>
  public static partial class Simple2DWorldReflection {

    #region Descriptor
    /// <summary>File descriptor for Simple2DWorld.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Simple2DWorldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNTaW1wbGUyRFdvcmxkLnByb3RvEiFDeWJlckxpZmUuUHJvdG9idWZmLlNp",
            "bXBsZTJEV29ybGQaDm1ldGFkYXRhLnByb3RvIqQBChVTaW1wbGUyRFdvcmxk",
            "TWV0YWRhdGESQgoNd29ybGRtZXRhZGF0YRgBIAEoCzIrLkN5YmVyTGlmZS5Q",
            "cm90b2J1ZmYuTWV0YWRhdGEuV29ybGRNZXRhZGF0YRJHCg9vcmdhbmljTWV0",
            "YWRhdGEYAiADKAsyLi5DeWJlckxpZmUuUHJvdG9idWZmLk1ldGFkYXRhLkxp",
            "ZmVGb3JtTWV0YWRhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CyberLife.Protobuff.Metadata.MetadataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CyberLife.Protobuff.Simple2DWorld.Simple2DWorldMetadata), global::CyberLife.Protobuff.Simple2DWorld.Simple2DWorldMetadata.Parser, new[]{ "Worldmetadata", "OrganicMetadata" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Simple2DWorldMetadata : pb::IMessage<Simple2DWorldMetadata> {
    private static readonly pb::MessageParser<Simple2DWorldMetadata> _parser = new pb::MessageParser<Simple2DWorldMetadata>(() => new Simple2DWorldMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Simple2DWorldMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CyberLife.Protobuff.Simple2DWorld.Simple2DWorldReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Simple2DWorldMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Simple2DWorldMetadata(Simple2DWorldMetadata other) : this() {
      worldmetadata_ = other.worldmetadata_ != null ? other.worldmetadata_.Clone() : null;
      organicMetadata_ = other.organicMetadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Simple2DWorldMetadata Clone() {
      return new Simple2DWorldMetadata(this);
    }

    /// <summary>Field number for the "worldmetadata" field.</summary>
    public const int WorldmetadataFieldNumber = 1;
    private global::CyberLife.Protobuff.Metadata.WorldMetadata worldmetadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::CyberLife.Protobuff.Metadata.WorldMetadata Worldmetadata {
      get { return worldmetadata_; }
      set {
        worldmetadata_ = value;
      }
    }

    /// <summary>Field number for the "organicMetadata" field.</summary>
    public const int OrganicMetadataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::CyberLife.Protobuff.Metadata.LifeFormMetadata> _repeated_organicMetadata_codec
        = pb::FieldCodec.ForMessage(18, global::CyberLife.Protobuff.Metadata.LifeFormMetadata.Parser);
    private readonly pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.LifeFormMetadata> organicMetadata_ = new pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.LifeFormMetadata>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CyberLife.Protobuff.Metadata.LifeFormMetadata> OrganicMetadata {
      get { return organicMetadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Simple2DWorldMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Simple2DWorldMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Worldmetadata, other.Worldmetadata)) return false;
      if(!organicMetadata_.Equals(other.organicMetadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (worldmetadata_ != null) hash ^= Worldmetadata.GetHashCode();
      hash ^= organicMetadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (worldmetadata_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Worldmetadata);
      }
      organicMetadata_.WriteTo(output, _repeated_organicMetadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (worldmetadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Worldmetadata);
      }
      size += organicMetadata_.CalculateSize(_repeated_organicMetadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Simple2DWorldMetadata other) {
      if (other == null) {
        return;
      }
      if (other.worldmetadata_ != null) {
        if (worldmetadata_ == null) {
          worldmetadata_ = new global::CyberLife.Protobuff.Metadata.WorldMetadata();
        }
        Worldmetadata.MergeFrom(other.Worldmetadata);
      }
      organicMetadata_.Add(other.organicMetadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (worldmetadata_ == null) {
              worldmetadata_ = new global::CyberLife.Protobuff.Metadata.WorldMetadata();
            }
            input.ReadMessage(worldmetadata_);
            break;
          }
          case 18: {
            organicMetadata_.AddEntriesFrom(input, _repeated_organicMetadata_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
